# Generated by Django 5.2.2 on 2025-06-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessclass',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
